### PR TITLE
Previous posts endpoint

### PR DESCRIPTION
**Pull request by davidtheplatform**
If the start_post paramater is present in /api/messages it will get the 50 posts after that id. If the parameter is -1 or not present it returns the last 50 posts. This doesn’t break any existing code.
Example:
`GET /api/messages?start_post=10`
`[post 10, post 11, post 12…]`

### CODE REVIEW

**Comment by JoshAtticus** [comment]
> If the start_post paramater is present in /api/messages it will get the 50 posts after that id. If the parameter is -1 or not present it returns the last 50 posts. This doesn’t break any existing code. Example: `GET /api/messages?start_post=10` `[post 10, post 11, post 12…]`

Sounds awesome, will check it out at some point and get it merged

**Comment by JoshAtticus** [comment]
Hi @davidtheplatform, do you mind pulling the latest changes to your branch? Thanks

**Comment by JoshAtticus** [comment]
> > If the start_post paramater is present in /api/messages it will get the 50 posts after that id. If the parameter is -1 or not present it returns the last 50 posts. This doesn’t break any existing code. Example: `GET /api/messages?start_post=10` `[post 10, post 11, post 12…]`
> 
> Sounds awesome, will check it out at some point and get it merged

Looks awesome too! Only thing is it might be confusing to use since there's no endpoint for finding the newest post ID.

**Comment by davidtheplatform** [comment]
> > > If the start_post paramater is present in /api/messages it will get the 50 posts after that id. If the parameter is -1 or not present it returns the last 50 posts. This doesn’t break any existing code. Example: `GET /api/messages?start_post=10` `[post 10, post 11, post 12…]`
> > 
> > 
> > Sounds awesome, will check it out at some point and get it merged
> 
> Looks awesome too! Only thing is it might be confusing to use since there's no endpoint for finding the newest post ID.

If you don't include the start_post argument it returns the last 50 posts

**Comment by davidtheplatform** [comment]
> Hi @davidtheplatform, do you mind pulling the latest changes to your branch? Thanks

Done

**Comment by JoshAtticus** [comment]
> > Hi @davidtheplatform, do you mind pulling the latest changes to your branch? Thanks
> 
> Done

Awesome, will check it out again

**Comment by JoshAtticus** [comment]
Awesome

**Pull request merged**
